/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_HelloJNI */

#ifndef _Included_app_HelloJNI
#define _Included_app_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_app_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
