/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class application_HelloJNI */

#ifndef _Included_application_HelloJNI
#define _Included_application_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     application_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_application_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
